name: spectral_llm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _py-xgboost-mutex=2.0=cpu_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - nlohmann_json=3.12.0=h54a6638_1
  - python_abi=3.12=8_cp312
  - tzdata=2025c=hc9c84f9_1
  - _openmp_mutex=4.5=2_gnu
  - fonts-conda-forge=1=hc364b38_1
  - libegl=1.7.0=ha4b6fd6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - fonts-conda-ecosystem=1=0
  - libgcc=15.2.0=he0feb66_16
  - alsa-lib=1.2.15.3=hb03c661_0
  - aws-c-common=0.12.4=hb03c661_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - keyutils=1.6.3=hb9d3cd8_0
  - libbrotlicommon=1.1.0=hb03c661_4
  - libdeflate=1.25=h17f619e_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libstdcxx=15.2.0=h934c35e_16
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - yaml=0.2.5=h280c20c_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.3=hecca717_0
  - gflags=2.2.2=h5888daf_1005
  - graphite2=1.3.14=hecca717_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libdrm=2.4.125=hb03c661_1
  - libebm=0.7.0=h84d6215_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libgfortran=15.2.0=h69a702a_16
  - libpng=1.6.54=h421ea60_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.1.4=cpu_h97e353d_2
  - lz4-c=1.10.0=h5888daf_1
  - mysql-common=9.0.1=h266115a_6
  - pcre2=10.44=hc749103_2
  - pixman=0.46.4=h54a6638_1
  - readline=8.3=h853b02a_0
  - s2n=1.5.26=h5ac9029_0
  - snappy=1.2.2=h03e3b7b_1
  - tk=8.6.13=noxft_h366c992_103
  - wayland=1.24.0=hd6090a7_1
  - xorg-libsm=1.2.6=he73a12e_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - aws-c-io=0.22.0=h57f3b0d_1
  - brotli-bin=1.1.0=hb03c661_4
  - glog=0.7.1=hbabe93e_0
  - icu=75.1=he02047a_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libfreetype6=2.13.3=h48d6fc4_1
  - libglib=2.84.0=h2ff4ddf_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - mysql-libs=9.0.1=he0572af_6
  - qhull=2020.2=h434a139_5
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - brotli=1.1.0=hb03c661_4
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - lcms2=2.18=h0c24ade_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libfreetype=2.13.3=ha770c72_1
  - libglx=1.7.0=ha4b6fd6_2
  - libxml2=2.13.9=h04c0eec_0
  - openjpeg=2.5.4=h55fea9a_0
  - orc=2.2.1=hd747db4_0
  - python=3.12.12=hd63d673_2_cpython
  - re2=2025.11.05=h5301d42_0
  - xcb-util-image=0.4.0=hb711507_2
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - zeromq=4.3.5=h387f397_9
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - azure-core-cpp=1.16.0=h3a458e0_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py312h1289d80_4
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - cython=3.2.4=py312h68e6be4_0
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.1=pyhcf101f3_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - executing=2.2.1=pyhd8ed1ab_0
  - freetype=2.13.3=ha770c72_1
  - future=1.0.0=pyhd8ed1ab_2
  - greenlet=3.3.1=py312h1289d80_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py312h0a2e395_2
  - lark=1.3.1=pyhd8ed1ab_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libgl=1.7.0=ha4b6fd6_2
  - libgrpc=1.73.1=h3288cfb_1
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxslt=1.1.43=h7a3aeb2_0
  - llvmlite=0.46.0=py312h7424e68_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.15.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openldap=2.6.10=he970967_0
  - packaging=26.0=pyhcf101f3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pillow=11.3.0=py312h0e488c8_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pox=0.3.7=pyhcf101f3_0
  - ppft=1.7.8=pyhcf101f3_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - psutil=7.2.2=py312h5253ce2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - retrying=1.4.2=pyhe01879c_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.30.0=py312h868fb18_0
  - send2trash=2.1.0=pyha191276_0
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py312h961da02_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.5.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - zipp=3.23.0=pyhcf101f3_1
  - zope.event=6.1=pyhcf101f3_0
  - zope.interface=8.0.1=py312h5253ce2_1
  - async-lru=2.1.0=pyhcf101f3_0
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - babel=2.17.0=pyhd8ed1ab_0
  - bleach=6.3.0=pyhcf101f3_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cffi=2.0.0=py312h460c074_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonttools=4.61.1=py312h8a5da7c_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - libclang-cpp20.1=20.1.8=default_h99862b1_8
  - libclang13=21.1.0=default_h746c552_1
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libpq=17.7=h5c52fec_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - multiprocess=0.70.19=py312h5253ce2_0
  - numpy=2.3.5=py312h33ff503_1
  - openpyxl=3.1.5=py312h7f6eeab_3
  - overrides=7.7.0=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - plotly=6.5.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python-utils=3.9.1=pyhff2d567_1
  - referencing=0.37.0=pyhcf101f3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyhc90fa1f_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - _python_abi3_support=1.0=hd8ed1ab_2
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_2
  - arrow=1.4.0=pyhcf101f3_0
  - aws-crt-cpp=0.34.4=h60c762c_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - cairo=1.18.4=h3394656_0
  - contourpy=1.3.3=py312h0a2e395_4
  - flask=3.1.2=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - gevent=25.9.1=py312h2144f13_1
  - ipython=9.9.0=pyh53cf698_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - numba=0.63.1=py312hd1dde6f_0
  - pandas=3.0.0=py312h8ecdadd_0
  - pathos=0.3.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - pydantic-core=2.41.5=py312h868fb18_1
  - scipy=1.17.0=py312h54fa4ab_1
  - sqlalchemy=2.0.46=py312h5253ce2_1
  - typeguard=4.4.4=pyhd8ed1ab_0
  - zstandard=0.25.0=py312h5253ce2_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - harfbuzz=11.0.0=h76408a6_0
  - httpcore=1.0.9=pyh29332c3_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - matplotlib-base=3.10.6=py312he3d6523_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pygam=0.12.0=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - scikit-learn=1.8.0=np2py312h3226591_1
  - statsmodels=0.14.6=py312h4f23490_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - interpret-core=0.7.0=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - libarrow=21.0.0=h56a6dad_8_cpu
  - nbformat=5.10.4=pyhd8ed1ab_1
  - pandera-base=0.29.0=pyhd8ed1ab_0
  - pmdarima=2.0.4=py312h41a817b_2
  - py-xgboost=2.1.4=cpu_pyhf5c67e3_2
  - qt6-main=6.9.0=h6441bc3_0
  - requests=2.32.5=pyhcf101f3_1
  - salib=1.5.2=pyhd8ed1ab_0
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - shap=0.50.0=cpu_py312ha977375_0
  - dash=2.18.2=pyhd8ed1ab_2
  - ipykernel=7.1.0=pyha191276_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libparquet=21.0.0=h790f06f_8_cpu
  - nbclient=0.10.4=pyhd8ed1ab_0
  - pandera=0.29.0=hd8ed1ab_0
  - pyside6=6.9.0=py312h91f0f75_0
  - seaborn=0.13.2=hd8ed1ab_3
  - xgboost=2.1.4=cpu_pyhc1a9e11_2
  - dash_cytoscape=0.2.0=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - matplotlib=3.10.6=py312h7900ff3_1
  - missingno=0.5.2=pyhd8ed1ab_1
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - pyarrow-core=21.0.0=py312hc195796_2_cpu
  - interpret=0.7.0=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - jupyterlab=4.5.3=pyhd8ed1ab_0
  - pyarrow=21.0.0=py312h7900ff3_2
  - notebook=7.5.3=pyhcf101f3_0
  - jupyter=1.1.1=pyhd8ed1ab_1
prefix: /home/hwahanik/miniconda3/envs/spectral_llm
